### ISSUE TITLE
SEGV signal found in TransD

### ISSUE THREAD

**Issue by fCorleone** [thunlp/Fast-TransX#38]
A SEGV signal found when running program transD in TransD directory:
```
=================================================================
==8745==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7f46e86cd908 bp 0x7ffd676d5a30 sp 0x7ffd676d5350 T0)
    #0 0x7f46e86cd907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7f46e954c5d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7f46e954c749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x4034fa in init() /home/mfc_fuzz/Fast-TransX/transD/transD.cpp:170
    #4 0x40e088 in main /home/mfc_fuzz/Fast-TransX/transD/transD.cpp:626
    #5 0x7f46e869282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401cf8 in _start (/home/mfc_fuzz/Fast-TransX/transD/transD+0x401cf8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==8745==ABORTING
```

**Comment by fCorleone** [comment]
Another SEGV signal found when running test-transD:
```
=================================================================
==8385==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7efc8e845908 bp 0x7ffd4ca24770 sp 0x7ffd4ca24090 T0)
    #0 0x7efc8e845907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7efc8f3bb5d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7efc8f3bb749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x401d1a in init() /home/mfc_fuzz/Fast-TransX/transD/test_transD.cpp:55
    #4 0x40b60b in main /home/mfc_fuzz/Fast-TransX/transD/test_transD.cpp:416
    #5 0x7efc8e80a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401a78 in _start (/home/mfc_fuzz/Fast-TransX/transD/test_transD+0x401a78)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==8385==ABORTING
```

**Comment by fCorleone** [comment]
Another SEGV signal found in program ptranse:
```
=================================================================
==9301==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7f199b63c908 bp 0x7fff425f3d90 sp 0x7fff425f36b0 T0)
    #0 0x7f199b63c907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7f199c4bb5d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7f199c4bb749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x406dde in init() /home/mfc_fuzz/Fast-TransX/Fast-PTransE/ptranse.cpp:357
    #4 0x409fdc in main /home/mfc_fuzz/Fast-TransX/Fast-PTransE/ptranse.cpp:487
    #5 0x7f199b60182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401cc8 in _start (/home/mfc_fuzz/Fast-TransX/Fast-PTransE/ptranse+0x401cc8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==9301==ABORTING
```
This information occurred when I was running program ptranse.

**Comment by fCorleone** [comment]
Another SEGV found:
```
=================================================================
==6814==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7efd43c2d908 bp 0x7fffbee161c0 sp 0x7fffbee15ae0 T0)
    #0 0x7efd43c2d907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7efd447a35d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7efd447a3749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x401d63 in init() /home/mfc_fuzz/Fast-TransX/transE/test_transE.cpp:56
    #4 0x40ac4b in main /home/mfc_fuzz/Fast-TransX/transE/test_transE.cpp:378
    #5 0x7efd43bf282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401a88 in _start (/home/mfc_fuzz/Fast-TransX/transE/test_transE+0x401a88)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==6814==ABORTING
```
when running program test_transE

**Comment by THUCSTHanxu13** [comment]
I do not know what can cause this error, maybe you can use gdb to check the code on your dataset
